sudo: required
services:
  - docker

env:
  - NODE_VERSION=8-jessie
  - NODE_VERSION=10-jessie
  
script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t node:$NODE_VERSION --build-arg NODE_IMAGE="node:${NODE_VERSION}" . 
  - docker images
  - docker tag node:$NODE_VERSION $DOCKER_USERNAME/probot-hello:$NODE_VERSION-$(git rev-parse HEAD)     #must have a repository created on hub.docker.com git-rev assigns a unique SHA to to the image tag
  - docker push $DOCKER_USERNAME/probot-hello:$NODE_VERSION-$(git rev-parse HEAD)

stages: 
  - test
  - npm-targets

jobs:
  include:
######################## 8-jessie #######################
    - stage: npm-targets
      name: "Test 8-jessie"
      install: skip
      script:
      - docker run --rm $DOCKER_USERNAME/probot-hello:$NODE_VERSION-$(git rev-parse HEAD) npm run $NPM_TARGET
      env:
      - NODE_VERSION=8-jessie
      - NPM_TARGET=test
    - stage: npm-targets
      name: "Test 8-jessie"
      install: skip
      script:
      - docker run --rm $DOCKER_USERNAME/probot-hello:$NODE_VERSION-$(git rev-parse HEAD) npm run $NPM_TARGET
      env:
      - NODE_VERSION=8-jessie
      - NPM_TARGET=lint
    - stage: npm-targets
      name: "Test 8-jessie"
      install: skip
      script:
      - docker run --rm $DOCKER_USERNAME/probot-hello:$NODE_VERSION-$(git rev-parse HEAD) npm run $NPM_TARGET
      env:
      - NODE_VERSION=8-jessie
      - NPM_TARGET=coverage

######################## 10-jessie #######################
    - stage: npm-targets
      name: "Test 10-jessie"
      install: skip
      script:
      - docker run --rm $DOCKER_USERNAME/probot-hello:$NODE_VERSION-$(git rev-parse HEAD) npm run $NPM_TARGET
      env:
      - NODE_VERSION=10-jessie
      - NPM_TARGET=test
    - stage: npm-targets
      name: "Test 10-jessie"
      install: skip
      script:
      - docker run --rm $DOCKER_USERNAME/probot-hello:$NODE_VERSION-$(git rev-parse HEAD) npm run $NPM_TARGET
      env:
      - NODE_VERSION=10-jessie
      - NPM_TARGET=lint
    - stage: npm-targets
      name: "Test 10-jessie"
      install: skip
      script:
      - docker run --rm $DOCKER_USERNAME/probot-hello:$NODE_VERSION-$(git rev-parse HEAD) npm run $NPM_TARGET

      if: branch = master
      env:
      - NODE_VERSION=10-jessie
      - NPM_TARGET=coverage

after_success:
  - set -x -v;
    set -e;
    if ["${NPM_TARGET}"= "test"]; then
       docker tag probot-hello probot-hello:$(git rev-parse HEAD);
    else
      echo "Skipping docker tagging of image";
    fi;
    docker images;
    set +x +v;

